(ns schema-doc
  "Generate `docs/schema.md` from the live schema (spec section 4).

  Generated, not written: a hand-maintained schema document is a document that
  is wrong. Run after adding a migration:

    clojure -M:dev -e \"(require 'schema-doc)(schema-doc/-main)\""
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [vulcan.store.db :as db]
            [vulcan.store.migrate :as migrate]))

(def out-file "docs/schema.md")

(defn- columns [conn table]
  (db/execute! conn ["SELECT column_name, data_type, is_nullable
                      FROM information_schema.columns
                      WHERE table_name = ?
                      ORDER BY ordinal_position" table]))

(defn- relations [conn kind]
  (->> (db/execute! conn ["SELECT table_name, table_type
                           FROM information_schema.tables
                           WHERE table_schema = 'main'
                           ORDER BY table_name"])
       (filter #(= kind (:table-type %)))
       (map :table-name)))

(defn- table-section [conn table]
  (str "### `" table "`\n\n"
       "| column | type | null |\n|---|---|---|\n"
       (str/join "\n"
                 (for [{:keys [column-name data-type is-nullable]} (columns conn table)]
                   (format "| `%s` | %s | %s |" column-name data-type
                           (if (= "YES" is-nullable) "yes" "no"))))
       "\n"))

(defn generate []
  (let [conn (migrate/open! (db/memory-connection))]
    (try
      (str "# Store schema\n\n"
           "*Generated by `dev/schema_doc.clj` from the migrations in "
           "`resources/sql/`. Do not edit by hand.*\n\n"
           "DuckDB " (db/duckdb-version conn)
           ". Migrations applied: " (str/join ", " (migrate/applied conn)) ".\n\n"
           "The store is append-only with idempotent upsert: re-ingesting a\n"
           "report is a no-op, and every identity is derived from content\n"
           "rather than from a sequence, so two stores built independently can\n"
           "be merged with `INSERT ... ON CONFLICT DO NOTHING` (spec §5.1).\n\n"
           "## Views\n\n"
           "Views are the contract between the store and the analysis layer.\n"
           "The analysis layer queries views; nothing above it queries base\n"
           "tables (spec §5.4).\n\n"
           (str/join "\n" (map #(table-section conn %) (relations conn "VIEW")))
           "\n## Tables\n\n"
           (str/join "\n" (map #(table-section conn %) (relations conn "BASE TABLE"))))
      (finally (db/close! conn)))))

(defn -main [& _]
  (io/make-parents out-file)
  (spit out-file (generate))
  (println "wrote" out-file (.length (io/file out-file)) "bytes"))
